name: Generate Snake
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: malikmajid161
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%2364ffda&color_dots=%2316213e,%230f3460,%23112240,%23233554,%2364ffda
